# Generated by Django 3.2.7 on 2021-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('dream', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('hometown', models.CharField(max_length=50)),
            ],
        ),
    ]
